version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-nubox
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password_2025"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-nubox-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password_2025", "SELECT 1"]
      interval: 10s
      retries: 10
volumes:
  mssql-nubox-data:
